version: "3"

tasks:
  build:
    cmds:
      - echo "Exporting Sonr Highway Dashboard Frontend"
      - yarn install && yarn export

  serve:
    cmds:
      - echo "Running Sonr Highway Node"
      - go run highway.go

  buf:
    dir: proto
    cmds:
      - buf mod update
      - buf build
      - buf push
      - protoc --doc_out=.../docs/static/json --doc_opt=json,proto_workspace.json ./proto/**/*.proto
