// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: v1/motor.proto

// Package Motor is used for defining a Motor node and its properties.

package v1

import (
	v1 "github.com/sonr-io/sonr/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializeRequest_IPAddress_Family int32

const (
	InitializeRequest_IPAddress_FAMILY_UNSPECIFIED InitializeRequest_IPAddress_Family = 0
	InitializeRequest_IPAddress_FAMILY_IPV4        InitializeRequest_IPAddress_Family = 1 // IPv4 Address
	InitializeRequest_IPAddress_FAMILY_IPV6        InitializeRequest_IPAddress_Family = 2 // IPv6 Address
)

// Enum value maps for InitializeRequest_IPAddress_Family.
var (
	InitializeRequest_IPAddress_Family_name = map[int32]string{
		0: "FAMILY_UNSPECIFIED",
		1: "FAMILY_IPV4",
		2: "FAMILY_IPV6",
	}
	InitializeRequest_IPAddress_Family_value = map[string]int32{
		"FAMILY_UNSPECIFIED": 0,
		"FAMILY_IPV4":        1,
		"FAMILY_IPV6":        2,
	}
)

func (x InitializeRequest_IPAddress_Family) Enum() *InitializeRequest_IPAddress_Family {
	p := new(InitializeRequest_IPAddress_Family)
	*p = x
	return p
}

func (x InitializeRequest_IPAddress_Family) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InitializeRequest_IPAddress_Family) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_motor_proto_enumTypes[0].Descriptor()
}

func (InitializeRequest_IPAddress_Family) Type() protoreflect.EnumType {
	return &file_v1_motor_proto_enumTypes[0]
}

func (x InitializeRequest_IPAddress_Family) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InitializeRequest_IPAddress_Family.Descriptor instead.
func (InitializeRequest_IPAddress_Family) EnumDescriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{0, 4, 0}
}

// -----------------------------------------------------------------------------
// Motor Node API
// -----------------------------------------------------------------------------
// (Client) InitializeRequest Message to Establish Sonr Host/API/Room
type InitializeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location         *v1.Location                      `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`                                                                                           // Current Runtime Location
	Profile          *v1.Profile                       `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`                                                                                             // Users Contact Card
	Connection       v1.Connection                     `protobuf:"varint,3,opt,name=connection,proto3,enum=common.v1.Connection" json:"connection,omitempty"`                                                            // Internet Connection Type
	HostOptions      *InitializeRequest_HostOptions    `protobuf:"bytes,4,opt,name=host_options,json=hostOptions,proto3" json:"host_options,omitempty"`                                                                  // Libp2p Host config
	ServiceOptions   *InitializeRequest_ServiceOptions `protobuf:"bytes,5,opt,name=service_options,json=serviceOptions,proto3" json:"service_options,omitempty"`                                                         // Service Config
	DeviceOptions    *InitializeRequest_DeviceOptions  `protobuf:"bytes,6,opt,name=device_options,json=deviceOptions,proto3" json:"device_options,omitempty"`                                                            // File System Config
	Variables        map[string]string                 `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Domain TXT Records
	WalletPassphrase string                            `protobuf:"bytes,8,opt,name=wallet_passphrase,json=walletPassphrase,proto3" json:"wallet_passphrase,omitempty"`                                                   // Wallet Passphrase
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetLocation() *v1.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *InitializeRequest) GetProfile() *v1.Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *InitializeRequest) GetConnection() v1.Connection {
	if x != nil {
		return x.Connection
	}
	return v1.Connection(0)
}

func (x *InitializeRequest) GetHostOptions() *InitializeRequest_HostOptions {
	if x != nil {
		return x.HostOptions
	}
	return nil
}

func (x *InitializeRequest) GetServiceOptions() *InitializeRequest_ServiceOptions {
	if x != nil {
		return x.ServiceOptions
	}
	return nil
}

func (x *InitializeRequest) GetDeviceOptions() *InitializeRequest_DeviceOptions {
	if x != nil {
		return x.DeviceOptions
	}
	return nil
}

func (x *InitializeRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *InitializeRequest) GetWalletPassphrase() string {
	if x != nil {
		return x.WalletPassphrase
	}
	return ""
}

// (Client) ShareRequest is request to share supplied files/urls with a peer
type ShareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer  *v1.Peer         `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`   // Peer to Share with
	Items []*v1.SupplyItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // Supply Items to share
}

func (x *ShareRequest) Reset() {
	*x = ShareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRequest) ProtoMessage() {}

func (x *ShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRequest.ProtoReflect.Descriptor instead.
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{1}
}

func (x *ShareRequest) GetPeer() *v1.Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ShareRequest) GetItems() []*v1.SupplyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// (Client) DecideRequest is request to respond to a share request
type DecideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decision bool     `protobuf:"varint,1,opt,name=decision,proto3" json:"decision,omitempty"` // True if Supply is Active
	Peer     *v1.Peer `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`          // Peer to Share with
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{2}
}

func (x *DecideRequest) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *DecideRequest) GetPeer() *v1.Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

// (Client) SearchRequest is Message for Searching for Peer
type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Query:
	//	*SearchRequest_SName
	//	*SearchRequest_PeerId
	Query isSearchRequest_Query `protobuf_oneof:"query"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{3}
}

func (m *SearchRequest) GetQuery() isSearchRequest_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (x *SearchRequest) GetSName() string {
	if x, ok := x.GetQuery().(*SearchRequest_SName); ok {
		return x.SName
	}
	return ""
}

func (x *SearchRequest) GetPeerId() string {
	if x, ok := x.GetQuery().(*SearchRequest_PeerId); ok {
		return x.PeerId
	}
	return ""
}

type isSearchRequest_Query interface {
	isSearchRequest_Query()
}

type SearchRequest_SName struct {
	SName string `protobuf:"bytes,1,opt,name=s_name,json=sName,proto3,oneof"` // SName combined with Device ID and Hashed
}

type SearchRequest_PeerId struct {
	PeerId string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3,oneof"` // Peer ID
}

func (*SearchRequest_SName) isSearchRequest_Query() {}

func (*SearchRequest_PeerId) isSearchRequest_Query() {}

type OnLobbyRefreshRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnLobbyRefreshRequest) Reset() {
	*x = OnLobbyRefreshRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnLobbyRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLobbyRefreshRequest) ProtoMessage() {}

func (x *OnLobbyRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLobbyRefreshRequest.ProtoReflect.Descriptor instead.
func (*OnLobbyRefreshRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{4}
}

type OnMailboxMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnMailboxMessageRequest) Reset() {
	*x = OnMailboxMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnMailboxMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnMailboxMessageRequest) ProtoMessage() {}

func (x *OnMailboxMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnMailboxMessageRequest.ProtoReflect.Descriptor instead.
func (*OnMailboxMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{5}
}

type OnTransmitDecisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnTransmitDecisionRequest) Reset() {
	*x = OnTransmitDecisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitDecisionRequest) ProtoMessage() {}

func (x *OnTransmitDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitDecisionRequest.ProtoReflect.Descriptor instead.
func (*OnTransmitDecisionRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{6}
}

type OnTransmitInviteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnTransmitInviteRequest) Reset() {
	*x = OnTransmitInviteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitInviteRequest) ProtoMessage() {}

func (x *OnTransmitInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitInviteRequest.ProtoReflect.Descriptor instead.
func (*OnTransmitInviteRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{7}
}

type OnTransmitProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnTransmitProgressRequest) Reset() {
	*x = OnTransmitProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitProgressRequest) ProtoMessage() {}

func (x *OnTransmitProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitProgressRequest.ProtoReflect.Descriptor instead.
func (*OnTransmitProgressRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{8}
}

type OnTransmitCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnTransmitCompleteRequest) Reset() {
	*x = OnTransmitCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitCompleteRequest) ProtoMessage() {}

func (x *OnTransmitCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitCompleteRequest.ProtoReflect.Descriptor instead.
func (*OnTransmitCompleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{9}
}

// (Client) ShareResponse is response to ShareRequest
type ShareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True if Supply is Active
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error Message if Supply is not Active
}

func (x *ShareResponse) Reset() {
	*x = ShareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareResponse) ProtoMessage() {}

func (x *ShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareResponse.ProtoReflect.Descriptor instead.
func (*ShareResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{10}
}

func (x *ShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// (Client) RespondResponse is response to RespondRequest
type DecideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True if Supply is Active
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error Message if Supply is not Active
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{11}
}

func (x *DecideResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DecideResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// (Client) SearchResponse is Message for Searching for Peer
type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`            // Success
	Error   string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                 // Error Message
	Peer    *v1.Peer `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`                   // Peer Data
	PeerId  string   `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // Peer ID
	SName   string   `protobuf:"bytes,5,opt,name=s_name,json=sName,proto3" json:"s_name,omitempty"`    // SName
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchResponse) GetPeer() *v1.Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *SearchResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SearchResponse) GetSName() string {
	if x != nil {
		return x.SName
	}
	return ""
}

// DecisionEvent is emitted when a decision is made by Peer.
type OnTransmitDecisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decision bool     `protobuf:"varint,1,opt,name=decision,proto3" json:"decision,omitempty"` // true = accept, false = reject
	From     *v1.Peer `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`          // Peer that made decision
	Received int64    `protobuf:"varint,3,opt,name=received,proto3" json:"received,omitempty"` // Timestamp
}

func (x *OnTransmitDecisionResponse) Reset() {
	*x = OnTransmitDecisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitDecisionResponse) ProtoMessage() {}

func (x *OnTransmitDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitDecisionResponse.ProtoReflect.Descriptor instead.
func (*OnTransmitDecisionResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{13}
}

func (x *OnTransmitDecisionResponse) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *OnTransmitDecisionResponse) GetFrom() *v1.Peer {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *OnTransmitDecisionResponse) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

// Message Sent when peer messages Lobby
type OnLobbyRefreshResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Olc      string     `protobuf:"bytes,1,opt,name=olc,proto3" json:"olc,omitempty"`            // OLC Code of Topic
	Peers    []*v1.Peer `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`        // User Information
	Received int64      `protobuf:"varint,3,opt,name=received,proto3" json:"received,omitempty"` // Invite received Timestamp
}

func (x *OnLobbyRefreshResponse) Reset() {
	*x = OnLobbyRefreshResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnLobbyRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLobbyRefreshResponse) ProtoMessage() {}

func (x *OnLobbyRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLobbyRefreshResponse.ProtoReflect.Descriptor instead.
func (*OnLobbyRefreshResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{14}
}

func (x *OnLobbyRefreshResponse) GetOlc() string {
	if x != nil {
		return x.Olc
	}
	return ""
}

func (x *OnLobbyRefreshResponse) GetPeers() []*v1.Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *OnLobbyRefreshResponse) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

// InviteEvent notifies Peer that an Invite has been received
type OnTransmitInviteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Received int64       `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"` // Invite received Timestamp
	From     *v1.Peer    `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`          // Peer that sent the Invite
	Payload  *v1.Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`    // Attached Data
}

func (x *OnTransmitInviteResponse) Reset() {
	*x = OnTransmitInviteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitInviteResponse) ProtoMessage() {}

func (x *OnTransmitInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitInviteResponse.ProtoReflect.Descriptor instead.
func (*OnTransmitInviteResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{15}
}

func (x *OnTransmitInviteResponse) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *OnTransmitInviteResponse) GetFrom() *v1.Peer {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *OnTransmitInviteResponse) GetPayload() *v1.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Received Mail Event
type OnMailboxMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // ID is the Message ID
	Buffer   []byte       `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`     // Buffer is the message data
	From     *v1.Profile  `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`         // Users Peer Data
	To       *v1.Profile  `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`             // Receivers Peer Data
	Metadata *v1.Metadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"` // Metadata
}

func (x *OnMailboxMessageResponse) Reset() {
	*x = OnMailboxMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnMailboxMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnMailboxMessageResponse) ProtoMessage() {}

func (x *OnMailboxMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnMailboxMessageResponse.ProtoReflect.Descriptor instead.
func (*OnMailboxMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{16}
}

func (x *OnMailboxMessageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OnMailboxMessageResponse) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *OnMailboxMessageResponse) GetFrom() *v1.Profile {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *OnMailboxMessageResponse) GetTo() *v1.Profile {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *OnMailboxMessageResponse) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Transfer Progress Event
type OnTransmitProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress  float64      `protobuf:"fixed64,1,opt,name=progress,proto3" json:"progress,omitempty"`                           // Current Transfer Progress
	Received  int64        `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`                            // Timestamp
	Current   int32        `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`                              // Current position of item in list
	Total     int32        `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`                                  // Total number of items in list
	Direction v1.Direction `protobuf:"varint,5,opt,name=direction,proto3,enum=common.v1.Direction" json:"direction,omitempty"` // Direction of Transfer
}

func (x *OnTransmitProgressResponse) Reset() {
	*x = OnTransmitProgressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitProgressResponse) ProtoMessage() {}

func (x *OnTransmitProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitProgressResponse.ProtoReflect.Descriptor instead.
func (*OnTransmitProgressResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{17}
}

func (x *OnTransmitProgressResponse) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *OnTransmitProgressResponse) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *OnTransmitProgressResponse) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *OnTransmitProgressResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OnTransmitProgressResponse) GetDirection() v1.Direction {
	if x != nil {
		return x.Direction
	}
	return v1.Direction(0)
}

// Message Sent after Completed Transfer
type OnTransmitCompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction  v1.Direction   `protobuf:"varint,1,opt,name=direction,proto3,enum=common.v1.Direction" json:"direction,omitempty"`                                                             // Direction of Transfer
	Payload    *v1.Payload    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                                                                           // Transfer Data
	From       *v1.Peer       `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`                                                                                                 // Peer that sent the Complete Event
	To         *v1.Peer       `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`                                                                                                     // Peer that received the Complete Event
	CreatedAt  int64          `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                                     // Transfer Created Timestamp
	ReceivedAt int64          `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`                                                                  // Transfer Received Timestamp
	Results    map[int32]bool `protobuf:"bytes,7,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // Transfer Success
}

func (x *OnTransmitCompleteResponse) Reset() {
	*x = OnTransmitCompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTransmitCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTransmitCompleteResponse) ProtoMessage() {}

func (x *OnTransmitCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTransmitCompleteResponse.ProtoReflect.Descriptor instead.
func (*OnTransmitCompleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{18}
}

func (x *OnTransmitCompleteResponse) GetDirection() v1.Direction {
	if x != nil {
		return x.Direction
	}
	return v1.Direction(0)
}

func (x *OnTransmitCompleteResponse) GetPayload() *v1.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OnTransmitCompleteResponse) GetFrom() *v1.Peer {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *OnTransmitCompleteResponse) GetTo() *v1.Peer {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *OnTransmitCompleteResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OnTransmitCompleteResponse) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *OnTransmitCompleteResponse) GetResults() map[int32]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

// Optional Message to Initialize FileSystem
type InitializeRequest_DeviceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Device ID
	HomeDir    string `protobuf:"bytes,2,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	SupportDir string `protobuf:"bytes,3,opt,name=support_dir,json=supportDir,proto3" json:"support_dir,omitempty"`
	TempDir    string `protobuf:"bytes,4,opt,name=temp_dir,json=tempDir,proto3" json:"temp_dir,omitempty"`
}

func (x *InitializeRequest_DeviceOptions) Reset() {
	*x = InitializeRequest_DeviceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeRequest_DeviceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest_DeviceOptions) ProtoMessage() {}

func (x *InitializeRequest_DeviceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest_DeviceOptions.ProtoReflect.Descriptor instead.
func (*InitializeRequest_DeviceOptions) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{0, 1}
}

func (x *InitializeRequest_DeviceOptions) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitializeRequest_DeviceOptions) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

func (x *InitializeRequest_DeviceOptions) GetSupportDir() string {
	if x != nil {
		return x.SupportDir
	}
	return ""
}

func (x *InitializeRequest_DeviceOptions) GetTempDir() string {
	if x != nil {
		return x.TempDir
	}
	return ""
}

// Libp2p Host Options
type InitializeRequest_HostOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuicTransport bool                           `protobuf:"varint,1,opt,name=quic_transport,json=quicTransport,proto3" json:"quic_transport,omitempty"` // Enable QUIC Transport
	HttpTransport bool                           `protobuf:"varint,2,opt,name=http_transport,json=httpTransport,proto3" json:"http_transport,omitempty"` // Enable HTTP Transport
	Ipv4Only      bool                           `protobuf:"varint,3,opt,name=ipv4_only,json=ipv4Only,proto3" json:"ipv4_only,omitempty"`                // Enable IPv4 Only
	ListenAddrs   []*InitializeRequest_IPAddress `protobuf:"bytes,4,rep,name=listen_addrs,json=listenAddrs,proto3" json:"listen_addrs,omitempty"`        // List of Listen Addresses (optional)
}

func (x *InitializeRequest_HostOptions) Reset() {
	*x = InitializeRequest_HostOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeRequest_HostOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest_HostOptions) ProtoMessage() {}

func (x *InitializeRequest_HostOptions) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest_HostOptions.ProtoReflect.Descriptor instead.
func (*InitializeRequest_HostOptions) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{0, 2}
}

func (x *InitializeRequest_HostOptions) GetQuicTransport() bool {
	if x != nil {
		return x.QuicTransport
	}
	return false
}

func (x *InitializeRequest_HostOptions) GetHttpTransport() bool {
	if x != nil {
		return x.HttpTransport
	}
	return false
}

func (x *InitializeRequest_HostOptions) GetIpv4Only() bool {
	if x != nil {
		return x.Ipv4Only
	}
	return false
}

func (x *InitializeRequest_HostOptions) GetListenAddrs() []*InitializeRequest_IPAddress {
	if x != nil {
		return x.ListenAddrs
	}
	return nil
}

// Service Configuration
type InitializeRequest_ServiceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Textile  bool  `protobuf:"varint,1,opt,name=textile,proto3" json:"textile,omitempty"`   // Enable Textile Client and Threads
	Mailbox  bool  `protobuf:"varint,2,opt,name=mailbox,proto3" json:"mailbox,omitempty"`   // Enable Mailbox
	Buckets  bool  `protobuf:"varint,3,opt,name=buckets,proto3" json:"buckets,omitempty"`   // Enable Buckets
	Interval int32 `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"` // Auto Update Interval (seconds) - Default 5s
}

func (x *InitializeRequest_ServiceOptions) Reset() {
	*x = InitializeRequest_ServiceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeRequest_ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest_ServiceOptions) ProtoMessage() {}

func (x *InitializeRequest_ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest_ServiceOptions.ProtoReflect.Descriptor instead.
func (*InitializeRequest_ServiceOptions) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{0, 3}
}

func (x *InitializeRequest_ServiceOptions) GetTextile() bool {
	if x != nil {
		return x.Textile
	}
	return false
}

func (x *InitializeRequest_ServiceOptions) GetMailbox() bool {
	if x != nil {
		return x.Mailbox
	}
	return false
}

func (x *InitializeRequest_ServiceOptions) GetBuckets() bool {
	if x != nil {
		return x.Buckets
	}
	return false
}

func (x *InitializeRequest_ServiceOptions) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

// IP Address Interface
type InitializeRequest_IPAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                       // Name of Interface
	Address  string                             `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                                 // IP Address of Interface
	Internal bool                               `protobuf:"varint,3,opt,name=internal,proto3" json:"internal,omitempty"`                                              // Wether it is a Loopback Interface
	Family   InitializeRequest_IPAddress_Family `protobuf:"varint,4,opt,name=family,proto3,enum=motor.v1.InitializeRequest_IPAddress_Family" json:"family,omitempty"` // Address Family
}

func (x *InitializeRequest_IPAddress) Reset() {
	*x = InitializeRequest_IPAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_motor_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeRequest_IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest_IPAddress) ProtoMessage() {}

func (x *InitializeRequest_IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_v1_motor_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest_IPAddress.ProtoReflect.Descriptor instead.
func (*InitializeRequest_IPAddress) Descriptor() ([]byte, []int) {
	return file_v1_motor_proto_rawDescGZIP(), []int{0, 4}
}

func (x *InitializeRequest_IPAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitializeRequest_IPAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *InitializeRequest_IPAddress) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *InitializeRequest_IPAddress) GetFamily() InitializeRequest_IPAddress_Family {
	if x != nil {
		return x.Family
	}
	return InitializeRequest_IPAddress_FAMILY_UNSPECIFIED
}

var File_v1_motor_proto protoreflect.FileDescriptor

var file_v1_motor_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x0d, 0x76, 0x31, 0x2f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x76, 0x31, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x09, 0x0a, 0x11, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2c, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x6f, 0x74,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x68, 0x6f, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x53, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x6f, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x50, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x48, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x6f, 0x74,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x12, 0x2b, 0x0a, 0x11, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73,
	0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x1a, 0x3c,
	0x0a, 0x0e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x76, 0x0a, 0x0d,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x68, 0x6f, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x6d,
	0x70, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x6d,
	0x70, 0x44, 0x69, 0x72, 0x1a, 0xc2, 0x01, 0x0a, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x71, 0x75, 0x69, 0x63, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x71, 0x75,
	0x69, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0d, 0x68, 0x74, 0x74, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x70, 0x76, 0x34, 0x4f, 0x6e, 0x6c, 0x79, 0x12,
	0x48, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x73, 0x1a, 0x7a, 0x0a, 0x0e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x65, 0x78, 0x74, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x65,
	0x78, 0x74, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x1a, 0xdf, 0x01, 0x0a, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x44, 0x0a,
	0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e,
	0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x50, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x06, 0x66, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x22, 0x42, 0x0a, 0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x12, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f,
	0x49, 0x50, 0x56, 0x34, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59,
	0x5f, 0x49, 0x50, 0x56, 0x36, 0x10, 0x02, 0x22, 0x60, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x50, 0x0a, 0x0d, 0x44, 0x65, 0x63,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x0d, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x06,
	0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64,
	0x42, 0x07, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x4f, 0x6e, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a,
	0x19, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x44, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4f, 0x6e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x3f, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x40, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x95, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x79, 0x0a, 0x1a, 0x4f, 0x6e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x22, 0x6d, 0x0a, 0x16, 0x4f, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x6c, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x6c,
	0x63, 0x12, 0x25, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x18, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6d, 0x69, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x23, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0xbf, 0x01, 0x0a, 0x18, 0x4f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x22, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xb8, 0x01, 0x0a, 0x1a, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69,
	0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x32, 0x0a, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8d, 0x03,
	0x0a, 0x1a, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x23,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x1f, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x65, 0x72,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x4b, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x8e, 0x06,
	0x0a, 0x0c, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a,
	0x0a, 0x05, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x44, 0x65,
	0x63, 0x69, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d,
	0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0e, 0x4f, 0x6e, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x1f, 0x2e, 0x6d, 0x6f, 0x74,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6d, 0x6f,
	0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x5d, 0x0a, 0x10, 0x4f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x63, 0x0a, 0x12, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x44, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x6f,
	0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69,
	0x74, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x5d, 0x0a, 0x10, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6d, 0x69, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x6d, 0x6f, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d,
	0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d,
	0x69, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x63, 0x0a, 0x12, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d,
	0x69, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x23, 0x2e, 0x6d, 0x6f, 0x74,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x63, 0x0a, 0x12, 0x4f, 0x6e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x23, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x22,
	0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6e,
	0x72, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x6e, 0x72, 0x2f, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_motor_proto_rawDescOnce sync.Once
	file_v1_motor_proto_rawDescData = file_v1_motor_proto_rawDesc
)

func file_v1_motor_proto_rawDescGZIP() []byte {
	file_v1_motor_proto_rawDescOnce.Do(func() {
		file_v1_motor_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_motor_proto_rawDescData)
	})
	return file_v1_motor_proto_rawDescData
}

var file_v1_motor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_motor_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_v1_motor_proto_goTypes = []interface{}{
	(InitializeRequest_IPAddress_Family)(0),  // 0: motor.v1.InitializeRequest.IPAddress.Family
	(*InitializeRequest)(nil),                // 1: motor.v1.InitializeRequest
	(*ShareRequest)(nil),                     // 2: motor.v1.ShareRequest
	(*DecideRequest)(nil),                    // 3: motor.v1.DecideRequest
	(*SearchRequest)(nil),                    // 4: motor.v1.SearchRequest
	(*OnLobbyRefreshRequest)(nil),            // 5: motor.v1.OnLobbyRefreshRequest
	(*OnMailboxMessageRequest)(nil),          // 6: motor.v1.OnMailboxMessageRequest
	(*OnTransmitDecisionRequest)(nil),        // 7: motor.v1.OnTransmitDecisionRequest
	(*OnTransmitInviteRequest)(nil),          // 8: motor.v1.OnTransmitInviteRequest
	(*OnTransmitProgressRequest)(nil),        // 9: motor.v1.OnTransmitProgressRequest
	(*OnTransmitCompleteRequest)(nil),        // 10: motor.v1.OnTransmitCompleteRequest
	(*ShareResponse)(nil),                    // 11: motor.v1.ShareResponse
	(*DecideResponse)(nil),                   // 12: motor.v1.DecideResponse
	(*SearchResponse)(nil),                   // 13: motor.v1.SearchResponse
	(*OnTransmitDecisionResponse)(nil),       // 14: motor.v1.OnTransmitDecisionResponse
	(*OnLobbyRefreshResponse)(nil),           // 15: motor.v1.OnLobbyRefreshResponse
	(*OnTransmitInviteResponse)(nil),         // 16: motor.v1.OnTransmitInviteResponse
	(*OnMailboxMessageResponse)(nil),         // 17: motor.v1.OnMailboxMessageResponse
	(*OnTransmitProgressResponse)(nil),       // 18: motor.v1.OnTransmitProgressResponse
	(*OnTransmitCompleteResponse)(nil),       // 19: motor.v1.OnTransmitCompleteResponse
	nil,                                      // 20: motor.v1.InitializeRequest.VariablesEntry
	(*InitializeRequest_DeviceOptions)(nil),  // 21: motor.v1.InitializeRequest.DeviceOptions
	(*InitializeRequest_HostOptions)(nil),    // 22: motor.v1.InitializeRequest.HostOptions
	(*InitializeRequest_ServiceOptions)(nil), // 23: motor.v1.InitializeRequest.ServiceOptions
	(*InitializeRequest_IPAddress)(nil),      // 24: motor.v1.InitializeRequest.IPAddress
	nil,                                      // 25: motor.v1.OnTransmitCompleteResponse.ResultsEntry
	(*v1.Location)(nil),                      // 26: common.v1.Location
	(*v1.Profile)(nil),                       // 27: common.v1.Profile
	(v1.Connection)(0),                       // 28: common.v1.Connection
	(*v1.Peer)(nil),                          // 29: common.v1.Peer
	(*v1.SupplyItem)(nil),                    // 30: common.v1.SupplyItem
	(*v1.Payload)(nil),                       // 31: common.v1.Payload
	(*v1.Metadata)(nil),                      // 32: common.v1.Metadata
	(v1.Direction)(0),                        // 33: common.v1.Direction
}
var file_v1_motor_proto_depIdxs = []int32{
	26, // 0: motor.v1.InitializeRequest.location:type_name -> common.v1.Location
	27, // 1: motor.v1.InitializeRequest.profile:type_name -> common.v1.Profile
	28, // 2: motor.v1.InitializeRequest.connection:type_name -> common.v1.Connection
	22, // 3: motor.v1.InitializeRequest.host_options:type_name -> motor.v1.InitializeRequest.HostOptions
	23, // 4: motor.v1.InitializeRequest.service_options:type_name -> motor.v1.InitializeRequest.ServiceOptions
	21, // 5: motor.v1.InitializeRequest.device_options:type_name -> motor.v1.InitializeRequest.DeviceOptions
	20, // 6: motor.v1.InitializeRequest.variables:type_name -> motor.v1.InitializeRequest.VariablesEntry
	29, // 7: motor.v1.ShareRequest.peer:type_name -> common.v1.Peer
	30, // 8: motor.v1.ShareRequest.items:type_name -> common.v1.SupplyItem
	29, // 9: motor.v1.DecideRequest.peer:type_name -> common.v1.Peer
	29, // 10: motor.v1.SearchResponse.peer:type_name -> common.v1.Peer
	29, // 11: motor.v1.OnTransmitDecisionResponse.from:type_name -> common.v1.Peer
	29, // 12: motor.v1.OnLobbyRefreshResponse.peers:type_name -> common.v1.Peer
	29, // 13: motor.v1.OnTransmitInviteResponse.from:type_name -> common.v1.Peer
	31, // 14: motor.v1.OnTransmitInviteResponse.payload:type_name -> common.v1.Payload
	27, // 15: motor.v1.OnMailboxMessageResponse.from:type_name -> common.v1.Profile
	27, // 16: motor.v1.OnMailboxMessageResponse.to:type_name -> common.v1.Profile
	32, // 17: motor.v1.OnMailboxMessageResponse.metadata:type_name -> common.v1.Metadata
	33, // 18: motor.v1.OnTransmitProgressResponse.direction:type_name -> common.v1.Direction
	33, // 19: motor.v1.OnTransmitCompleteResponse.direction:type_name -> common.v1.Direction
	31, // 20: motor.v1.OnTransmitCompleteResponse.payload:type_name -> common.v1.Payload
	29, // 21: motor.v1.OnTransmitCompleteResponse.from:type_name -> common.v1.Peer
	29, // 22: motor.v1.OnTransmitCompleteResponse.to:type_name -> common.v1.Peer
	25, // 23: motor.v1.OnTransmitCompleteResponse.results:type_name -> motor.v1.OnTransmitCompleteResponse.ResultsEntry
	24, // 24: motor.v1.InitializeRequest.HostOptions.listen_addrs:type_name -> motor.v1.InitializeRequest.IPAddress
	0,  // 25: motor.v1.InitializeRequest.IPAddress.family:type_name -> motor.v1.InitializeRequest.IPAddress.Family
	2,  // 26: motor.v1.MotorService.Share:input_type -> motor.v1.ShareRequest
	3,  // 27: motor.v1.MotorService.Decide:input_type -> motor.v1.DecideRequest
	4,  // 28: motor.v1.MotorService.Search:input_type -> motor.v1.SearchRequest
	5,  // 29: motor.v1.MotorService.OnLobbyRefresh:input_type -> motor.v1.OnLobbyRefreshRequest
	6,  // 30: motor.v1.MotorService.OnMailboxMessage:input_type -> motor.v1.OnMailboxMessageRequest
	7,  // 31: motor.v1.MotorService.OnTransmitDecision:input_type -> motor.v1.OnTransmitDecisionRequest
	8,  // 32: motor.v1.MotorService.OnTransmitInvite:input_type -> motor.v1.OnTransmitInviteRequest
	9,  // 33: motor.v1.MotorService.OnTransmitProgress:input_type -> motor.v1.OnTransmitProgressRequest
	10, // 34: motor.v1.MotorService.OnTransmitComplete:input_type -> motor.v1.OnTransmitCompleteRequest
	11, // 35: motor.v1.MotorService.Share:output_type -> motor.v1.ShareResponse
	12, // 36: motor.v1.MotorService.Decide:output_type -> motor.v1.DecideResponse
	13, // 37: motor.v1.MotorService.Search:output_type -> motor.v1.SearchResponse
	15, // 38: motor.v1.MotorService.OnLobbyRefresh:output_type -> motor.v1.OnLobbyRefreshResponse
	17, // 39: motor.v1.MotorService.OnMailboxMessage:output_type -> motor.v1.OnMailboxMessageResponse
	14, // 40: motor.v1.MotorService.OnTransmitDecision:output_type -> motor.v1.OnTransmitDecisionResponse
	16, // 41: motor.v1.MotorService.OnTransmitInvite:output_type -> motor.v1.OnTransmitInviteResponse
	18, // 42: motor.v1.MotorService.OnTransmitProgress:output_type -> motor.v1.OnTransmitProgressResponse
	19, // 43: motor.v1.MotorService.OnTransmitComplete:output_type -> motor.v1.OnTransmitCompleteResponse
	35, // [35:44] is the sub-list for method output_type
	26, // [26:35] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_v1_motor_proto_init() }
func file_v1_motor_proto_init() {
	if File_v1_motor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_motor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnLobbyRefreshRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnMailboxMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitDecisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitInviteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitDecisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnLobbyRefreshResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitInviteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnMailboxMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitProgressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTransmitCompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeRequest_DeviceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeRequest_HostOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeRequest_ServiceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_motor_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeRequest_IPAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_motor_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SearchRequest_SName)(nil),
		(*SearchRequest_PeerId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_motor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_motor_proto_goTypes,
		DependencyIndexes: file_v1_motor_proto_depIdxs,
		EnumInfos:         file_v1_motor_proto_enumTypes,
		MessageInfos:      file_v1_motor_proto_msgTypes,
	}.Build()
	File_v1_motor_proto = out.File
	file_v1_motor_proto_rawDesc = nil
	file_v1_motor_proto_goTypes = nil
	file_v1_motor_proto_depIdxs = nil
}
